{
 "title": "http-server-projeto-korp",
 "panels": [
  {
   "title": "Disponibilidade do serviço",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "service_up" }
   ]
  },
  {
   "title": "Volume de requisições por segundo",
   "type": "timeseries",
   "gridPos": { "x": 6, "y": 0, "w": 18, "h": 8 },
   "targets": [
    {
     "expr": "rate(http_requests_total[1m])",
     "legendFormat": "{{method}} {{endpoint}} {{status}}"
    }
   ]
  },
  {
   "title": "Total de requisições",
   "type": "stat",
   "gridPos": { "x": 0, "y": 4, "w": 6, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(http_requests_total)" }
   ]
  }
 ]
}