---
- name: Aguardar o serviço estar disponível
  wait_for:
    host: localhost
    port: 80
    delay: 5
    timeout: 30

- name: Fazer requisição HTTP para o serviço
  uri:
    url: http://localhost:80/projeto-korp
    method: GET
    return_content: true
  register: response

- name: Exibir resposta no console
  debug:
    msg: "Resposta do serviço: {{ response.content }}"
