---
- name: Instalar dependências do Docker
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
    state: present
    update_cache: true

- name: Criar diretório para chaves GPG
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Adicionar chave GPG oficial do Docker
  shell: |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  args:
    creates: /etc/apt/keyrings/docker.gpg

- name: Adicionar repositório do Docker
  shell: |
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo $VERSION_CODENAME) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  args:
    creates: /etc/apt/sources.list.d/docker.list

- name: Instalar Docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present
    update_cache: true

- name: Garantir que o Docker está rodando
  service:
    name: docker
    state: started
    enabled: true

- name: Criar rede Docker korp-network
  community.docker.docker_network:
    name: korp-network
    driver: bridge
    state: present
